name: Deploy for Books API

on:
  push:
    branches: [main]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: SetUp Java
            uses: actions/setup-java@v3
            with:
              distribution: 'zulu'
              java-version: '17'

          - name: Build Project
            run: mvn clean install -DskipTests

          - name: Login Docker Hub
            run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

          - name: Build Docker image
            run: docker build -t ${{secrets.DOCKER_USERNAME}}/book-store-api .

          - name: Push image to docker hub
            run: docker push ${{secrets.DOCKER_USERNAME}}/book-store-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/book-store-api:latest

      - name: Remove container if exists
        run: docker rm -f book-store-api-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name book-store-api-container ${{secrets.DOCKER_USERNAME}}/book-store-api:latest
